### ISSUE TITLE
[FR] Add 'Hold to Pause' button to 'Scan Barcode' view

### ISSUE THREAD

**Issue by jacksonrya** [inventree/inventree-app#446] opened 2023-11-09 10:26 UTC
**Feature**
Include a button in the negative space of the camera feed (outside the scan zone) that, when held down, prevents the scanner from looking for QR/ Barcodes. Then, once the button is released, the scanner 'scans' and proceeds as normal.

**'Hold to Pause' vs. 'Click to Scan'**
Despite handheld scanners frequently having a trigger to 'turn on' the scan, the app's current functionality is always 'on', which conveniently provides quick scans on-the-fly. A 'Hold to Pause' option would provide more control to the user without forcing all users to adjust to a new scanning flow from the addition of a 'Click to Scan' button.

**Use Case/ User Story**
Inventory Manager is attempting to scan a QR/Barcode located in the middle of a sheet of QR/Barcodes.
*Currently, the phone would have to be perfectly aligned before the 'Scan Barcode' view is shown. Within the 'Scan Barcode' view, any panning across the sheet to find the correct code would potentially result in collecting an unwanted code.

Imagine the barcode sheets that grocery stores scan for produce at checkout, or that art stores scan for miscellaneous small items.
_Bare bones example of a QR print-out representing stock locations 1-40 (sorry dark mode users)_
![test](https://github.com/inventree/inventree-app/assets/9058130/8014b42a-cfa8-418d-be7d-11010925d199)

**Comment by SchrodingersGat** [comment] 2023-11-09 11:11
@jacksonrya this exact feature has been suggested and implemented over at https://github.com/inventree/inventree-app/pull/444 - how interesting that two people have a near identical use case in such a short timespan!

**Comment by Alex9779** [comment] 2023-11-09 12:00
> how interesting that two people have a near identical use case in such a short timespan

we live in a strange world 😃

**Comment by jacksonrya** [comment] 2023-11-10 02:17
Sorry y'all... I should've been more thorough in my issue search!

Looking forward to the merge and update!

Feel free to close :)

**Comment by SchrodingersGat** [comment] 2023-11-10 02:55
Duplicate of #444

**Closed as completed by SchrodingersGat** 2023-11-10 02:55 UTC
