### ISSUE TITLE
Label printing machine selection does not show

### ISSUE THREAD

**Issue by gid204** [inventree/inventree-app#544] opened 2024-10-04 00:02 UTC
Inventree Version: 0.16.3
iOS App Version: 0.16.5 - Build 91

When printing a label using the 'InvenTree machine label printer' plugin, the machine selection box does not appear:
![Image](https://github.com/user-attachments/assets/93bc5911-3275-4813-bf3d-01c48d29d927)

As comparison, here's what shows up on my desktop browser:
![Image](https://github.com/user-attachments/assets/bd8bc34c-c561-4451-b9e1-4084eb278aba)

**Comment by wolflu05** [comment] 2024-10-08 18:52
This is a duplicate of #472

@SchrodingersGat Are you planning on adding support for this?

**Comment by SchrodingersGat** [comment] 2024-10-09 11:10
@wolflu05 I'm not able to look into this right away - do you have any time to tackle it?

Edit: I see your other comment:

> Unfortunately I have no experience with flutter, so I'm not able to contribute that implementation.

**Comment by SchrodingersGat** [comment] 2024-10-09 11:11
Closing, as duplicate of https://github.com/inventree/inventree-app/issues/472

Please direct any comments to the other thread.

**Closed as completed** 2024-10-09 11:11 UTC
